"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name='impulse',
    version='1.0',
    py_modules=[
        'distortionchecker',
        'audio_spectrum.py'
        'functions', 
        'launcher', 
        'pulsecatcher', 
        'run',
        'server', 
        'shapecatcher', 
        'tab1', 
        'tab2', 
        'tab3', 
        'tab4',
        'tab5'
    ],
    app=['run.py'],
    options={
        'py2app': {
            'argv_emulation': True,
            'iconfile': 'favicon',
            'includes': [
                'dash',
                'dash_daq',
                'datetime',
                'flask',
                'jason',
                'numpy',
                'pandas',
                'pathlib',
                'plotly',
                'wave',
                'pyaudio',
                'scipy',
                'requests',
                'simpleaudio'
                ],  # Add 'numpy' as an included module
        }
    },
    setup_requires=['py2app'],
)








