"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import functions as fn
import os

datafolder = fn.get_path('data')

isotopes = fn.get_path('isotopes')

print('data directory: ', datafolder)

setup(
    name='impulse',
    version='1.0',
    py_modules=[
        'run','functions', 
        'launcher', 
        'pulsecatcher', 
        'server', 
        'shapecatcher', 
        'tab1', 
        'tab2', 
        'tab3', 
        'tab4'
        ],
    app=['run.py'],
    options={'py2app': {'argv_emulation': True, 'iconfile': 'favicon',}},
    data_files=[datafolder],

    setup_requires=['py2app'],
)







