import pyaudio
p = pyaudio.PyAudio()

info0 = p.get_device_info_by_host_api_device_index(0,0)
print(info0)
print(' ')
info1 = p.get_device_info_by_host_api_device_index(0,1)
print(info1)
print(' ')
info2 = p.get_device_info_by_host_api_device_index(0,2)
print(info2)
print(' ')
info3 = p.get_device_info_by_host_api_device_index(0,3)
print(info3)
print(' ')
info4 = p.get_device_info_by_host_api_device_index(0,4)
print(info4)
print(' ')
info5 = p.get_device_info_by_host_api_device_index(0,5)
print(info5)
print(' ')
info6 = p.get_device_info_by_host_api_device_index(0,6)
print(info6)
print(' ')
info7 = p.get_device_info_by_host_api_device_index(0,7)
print(info7)
print(' ')