[build-system]
requires = [
    "setuptools>=61.0",    # Modern setuptools for building
    "wheel",               # Needed for generating wheel files
    "py2app>=0.28.0"       # For macOS app bundling
]
build-backend = "setuptools.build_meta"

[project]
name = "impulse"
version = "2.2.9"
description = "A Python application for data analysis with a Dash interface"
dependencies = [
    "dash",
    "dash-bootstrap-components",
    "dash-daq",
    "numpy",
    "pandas",
    "plotly",
    "pyaudio",
    "requests",
    "scipy",
    "pyserial"  # Use 'pyserial' instead of 'serial' for clarity
]

[tool.py2app]
# Optional: You can move some py2app options here, but they typically stay in setup.py
# This section is just for reference; setup.py still handles most py2app config
options = { "iconfile" = "favicon.icns" }